install: true

language: generic

jobs:
    include:
    - stage: build
      os: osx
      osx_image: xcode11
      script: ./ci/dist_mac_os.sh

      deploy:
          provider: releases
          api_key: $RELEASE_TOKEN
          file: build/jpackage/lockbook-dev-desktop.app
          skip_cleanup: true
          on:
              tags: false
          name: Lockbook 0.$TRAVIS_BUILD_NUMBER MacOS
          body: $TRAVIS_COMMIT - $TRAVIS_COMMIT_MESSAGE - $(date +'%d.%m.%Y %R')
