install: true

language: java
os: linux
dist: trusty
jdk: oraclejdk11

script:
  - ./gradlew runtimeZip

deploy:
    provider: releases
    api_key: $RELEASE_TOKEN
    file: build/binaries.zip
    skip_cleanup: true
    on:
        tags: false
    name: Lockbook 0.$TRAVIS_BUILD_NUMBER
    body: $TRAVIS_COMMIT - $TRAVIS_COMMIT_MESSAGE - $(date +'%d.%m.%Y %R')

before_cache:
  - rm -rf  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
