install: true

language: generic

jobs:
    include:
    - stage: build
      name: "Dist MacOs"
      os: osx
      jdk: oraclejdk11
      osx_image: xcode11
      script: ./ci/dist_mac_os.sh
      deploy:
          provider: releases
          api_key: $RELEASE_TOKEN
          file: build/jpackage/lockbook-macos.tar.gz
          skip_cleanup: true
          on:
              tags: false
          name: Lockbook 0.$TRAVIS_BUILD_NUMBER
          body: $TRAVIS_COMMIT - $TRAVIS_COMMIT_MESSAGE - $(date +'%d.%m.%Y %R')

    - stage: build
      name: "Dist Linux"
      jdk: oraclejdk11
      os: linux
      dist: bionic
      script: ./ci/dist_linux.sh
      deploy:
          provider: releases
          api_key: $RELEASE_TOKEN
          file: build/jpackage/lockbook-linux.tar.gz
          skip_cleanup: true
          on:
              tags: false
          name: Lockbook 0.$TRAVIS_BUILD_NUMBER
          body: $TRAVIS_COMMIT - $TRAVIS_COMMIT_MESSAGE - $(date +'%d.%m.%Y %R')
