install: true

language: java
os: linux
dist: trusty
jdk: oraclejdk11

script:
  - ./gradlew runtime

deploy:
    before_deploy: "./gradlew runtimeZip && ls"
    provider: releases
    api_key: $RELEASE_TOKEN
    file: $HOME/build/image.zip
    skip_cleanup: true
    on:
        tags: false

before_cache:
  - rm -rf  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
